import { describe, expect, it } from 'vitest';
import { EN_STRINGS } from './locales/en';
import { OTHER_STRINGS, SUPPORTED_LANGUAGES } from './i18n';

const EN_KEYS = Object.keys(EN_STRINGS).sort();

function placeholders(value: string) {
  return (value.match(/\{(\w+)\}/g) ?? []).sort();
}

const NON_EN = SUPPORTED_LANGUAGES.filter((language) => language !== 'en');

describe('i18n locale parity', () => {
  it('registers a catalog for every supported non-English language', () => {
    for (const language of NON_EN) {
      expect(OTHER_STRINGS[language], `missing catalog for ${language}`).toBeDefined();
    }
  });

  it.each(NON_EN)('locale "%s" has exactly the English key set', (language) => {
    const catalog = OTHER_STRINGS[language];
    expect(catalog, `missing catalog for ${language}`).toBeDefined();

    const keys = Object.keys(catalog ?? {}).sort();
    const missing = EN_KEYS.filter((key) => !(key in (catalog ?? {})));
    const extra = keys.filter((key) => !(key in EN_STRINGS));

    expect(missing, `${language} is missing keys`).toEqual([]);
    expect(extra, `${language} has unknown keys`).toEqual([]);
  });

  it.each(NON_EN)('locale "%s" preserves all {placeholder} tokens', (language) => {
    const catalog = OTHER_STRINGS[language] ?? {};

    for (const key of EN_KEYS) {
      const translated = (catalog as Record<string, string>)[key];
      if (translated === undefined) {
        continue;
      }

      expect(
        placeholders(translated),
        `${language} → ${key} placeholder mismatch`,
      ).toEqual(placeholders((EN_STRINGS as Record<string, string>)[key]));
    }
  });

  // Keys whose value legitimately matches English in a given locale: verified
  // cognates, loanwords, and shared abbreviations ("Navigation" in German,
  // "min"/"h", "Emoji", "Online", …). A value identical to English that is
  // NOT listed here is the classic signature of a key added without
  // translating it — add a real translation, or extend this list only after
  // confirming the English form is the correct native term.
  const IDENTICAL_TO_ENGLISH_ALLOWLIST: Record<string, string[]> = {
    ar: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.composer.privateGroupBytesRemaining', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    he: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.composer.privateGroupBytesRemaining', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    ja: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.composer.privateGroupBytesRemaining', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    ko: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.composer.privateGroupBytesRemaining', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    ru: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.composer.privateGroupBytesRemaining', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    'zh-CN': ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.composer.privateGroupBytesRemaining', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    'zh-TW': ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.composer.privateGroupBytesRemaining', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    de: ['action.closedGroupSendUnsupported', 'aria.navigation', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.block', 'label.approval.windowEta', 'label.common.navigation', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'label.group.admin', 'label.group.global', 'label.member.online', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    el: ['action.closedGroupSendUnsupported', 'app.title', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    es: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.eta.hours', 'label.approval.eta.minutes', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'label.error', 'label.group.global', 'message.error', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    et: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.eta.hours', 'label.approval.eta.minutes', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    fi: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.eta.minutes', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    fr: ['action.closedGroupSendUnsupported', 'aria.navigation', 'button.mention', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.eta.hours', 'label.approval.eta.minutes', 'label.approval.signature', 'label.approval.type.unknown', 'label.common.direct', 'label.common.message', 'label.common.navigation', 'label.composer.privateGroupBytesRemaining', 'label.group.admin', 'label.group.global', 'label.invites', 'label.message', 'placeholder.message', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal', 'title.directPanel'],
    hi: ['action.closedGroupSendUnsupported', 'app.title', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.composer.privateGroupBytesRemaining', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    hu: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'label.group.admin', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    it: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.eta.hours', 'label.approval.eta.minutes', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'label.group.admin', 'label.member.online', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    nb: ['action.closedGroupSendUnsupported', 'app.title', 'button.privateGroup.publishKey', 'button.send', 'button.startMinting', 'group.status.minting.minting', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.eta.minutes', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'label.group.admin', 'label.group.global', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    nl: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.eta.minutes', 'label.common.direct', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'label.group.open', 'label.member.online', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal', 'title.directPanel'],
    pl: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.eta.minutes', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'label.member.online', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    pt: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.eta.hours', 'label.approval.eta.minutes', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'label.group.global', 'label.member.online', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
    ro: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.eta.hours', 'label.approval.eta.minutes', 'label.common.direct', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'label.group.global', 'label.member.online', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal', 'title.directPanel'],
    sv: ['action.closedGroupSendUnsupported', 'button.privateGroup.publishKey', 'hint.privateGroupNotMember', 'hint.privateGroupRotationRequired', 'label.approval.block', 'label.approval.eta.hours', 'label.approval.eta.minutes', 'label.approval.windowEta', 'label.composer.emoji', 'label.composer.privateGroupBytesRemaining', 'label.group.global', 'label.member.online', 'status.bridge.accountLocked', 'status.bridge.generic', 'status.bridge.missingGroupKey', 'status.bridge.missingRecipientPublicKey', 'status.bridge.nodeCapabilityMissing', 'status.bridge.notGroupMember', 'status.bridge.pendingJournalNotice', 'status.bridge.pendingReconciliationRequired', 'status.bridge.routeUnavailable', 'status.bridge.staleContext', 'status.bridge.validationFailed', 'status.loadingError.privateGroupState', 'status.privateGroupKey.missingAskAdmin', 'status.privateGroupKey.published', 'status.privateGroupKey.publishing', 'status.privateGroupKey.recoveredQortal'],
  };

  it.each(NON_EN)('locale "%s" has no unexpected untranslated values', (language) => {
    const catalog = (OTHER_STRINGS[language] ?? {}) as Record<string, string>;
    const allowed = new Set(IDENTICAL_TO_ENGLISH_ALLOWLIST[language] ?? []);
    const unexpectedIdentical = EN_KEYS.filter(
      (key) =>
        catalog[key] !== undefined &&
        catalog[key] === (EN_STRINGS as Record<string, string>)[key] &&
        !allowed.has(key),
    );

    expect(
      unexpectedIdentical,
      `${language} has values identical to English that are not in the cognate allowlist — translate them (or allowlist a confirmed cognate)`,
    ).toEqual([]);
  });
});
